### ISSUE TITLE
Question Regarding TEETrigger

### ISSUE THREAD

**Issue by syafiq** [Fraunhofer-AISEC/lazarus#7]
Hi!

Not sure if this is the right place to ask this question, but I can't see any better option to do this. I appreciate any help to clarify my understanding.

Let the device be D and the hub be H. My understanding after reading the [paper](https://dl.acm.org/doi/10.1145/3320269.3384723) is that if D stops sending awdt, then at some point, D will reset if the awdt expires, triggered by an internal clock.

Since lz_demo_hub is located in the unsecured flash, say an adversary is able to disable [this line](https://github.com/Fraunhofer-AISEC/lazarus/blob/7cf547028528bc734bc71510cdbca424b72a295c/lz_demo_app/lz_awdt.c#L65). I would expect the device to reset at some point. But, what I see in my local setup is that the device continues operating (without sending any awdt request of course). Is this intentional? 

Thanks a lot!

**Comment by smo4201** [comment]
Hi syafiq, 
sorry for the late reply. The default timeout is set to 3600s (1h). Did you wait for this time? You can set this to a lower value [here](https://github.com/Fraunhofer-AISEC/lazarus/blob/main/lz_common/lz_common/lz_common.h#L48) and then the device should do exactly as you said. Let me know if this solves your issue.
